from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from PIL import Image, ImageOps

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def to_posix(path: Path) -> str:
    return path.as_posix()


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def composite_on_dark(image: Image.Image) -> Image.Image:
    if image.mode in ("RGBA", "LA") or (image.mode == "P" and "transparency" in image.info):
        rgba = image.convert("RGBA")
        background = Image.new("RGBA", rgba.size, (5, 6, 6, 255))
        return Image.alpha_composite(background, rgba).convert("RGB")

    return image.convert("RGB")


def make_thumbnail(source: Path, target: Path, size: tuple[int, int], quality: int) -> dict[str, Any]:
    with Image.open(source) as image:
        image = ImageOps.exif_transpose(image)
        source_width, source_height = image.size
        image = composite_on_dark(image)
        thumbnail = ImageOps.fit(image, size, method=Image.Resampling.LANCZOS, centering=(0.5, 0.5))
        target.parent.mkdir(parents=True, exist_ok=True)
        thumbnail.save(target, "WEBP", quality=quality, method=6)

    return {
        "sourceWidth": source_width,
        "sourceHeight": source_height,
        "thumbnailWidth": size[0],
        "thumbnailHeight": size[1],
    }


def import_name(index: int, prefix: str) -> str:
    return f"{prefix}{index}"


def relative_import(from_file: Path, target: Path) -> str:
    relative = target.relative_to(project_root())
    return "../" + to_posix(relative.relative_to("src"))


def write_ts_map(map_path: Path, items: list[dict[str, Any]]) -> None:
    usable_items = [item for item in items if item.get("hasThumbnail")]
    map_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// Generated by scripts/generate-thumbnails.py. Do not edit by hand.",
        "",
    ]

    for index, item in enumerate(usable_items):
        source_import = import_name(index, "source")
        thumb_import = import_name(index, "thumb")
        lines.append(f'import {source_import} from "{relative_import(map_path, project_root() / item["source"])}";')
        lines.append(f'import {thumb_import} from "{relative_import(map_path, project_root() / item["thumbnail"])}";')

    lines.extend(
        [
            "",
            "const thumbnailPairs: [string, string][] = [",
        ],
    )

    for index, _item in enumerate(usable_items):
        lines.append(f"  [{import_name(index, 'source')}, {import_name(index, 'thumb')}],")

    lines.extend(
        [
            "];",
            "",
            "export const generatedThumbnails = new Map<string, string>(thumbnailPairs);",
            "",
            "export const getGeneratedThumbnail = (source: string | undefined, fallback = \"\") => {",
            "  if (!source) return fallback;",
            "  return (generatedThumbnails.get(source) ?? fallback) || source;",
            "};",
            "",
        ],
    )

    map_path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    root = project_root()
    parser = argparse.ArgumentParser(description="Generate gallery thumbnails and tracking manifest.")
    parser.add_argument("--source", default="src/assets/projects", help="Source image directory.")
    parser.add_argument("--out", default="src/assets/thumbnails/projects", help="Thumbnail output directory.")
    parser.add_argument(
        "--manifest",
        default="src/assets/thumbnails/thumbnail-manifest.json",
        help="JSON manifest path.",
    )
    parser.add_argument(
        "--map",
        default="src/data/generatedThumbnails.ts",
        help="Generated TypeScript source-to-thumbnail map.",
    )
    parser.add_argument("--width", type=int, default=480, help="Thumbnail width.")
    parser.add_argument("--height", type=int, default=270, help="Thumbnail height.")
    parser.add_argument("--quality", type=int, default=82, help="WebP quality.")
    parser.add_argument("--force", action="store_true", help="Regenerate thumbnails even when current.")
    args = parser.parse_args()

    args.source = (root / args.source).resolve()
    args.out = (root / args.out).resolve()
    args.manifest = (root / args.manifest).resolve()
    args.map = (root / args.map).resolve()
    return args


def main() -> int:
    args = parse_args()
    root = project_root()

    if not args.source.exists():
      raise FileNotFoundError(f"Source directory does not exist: {args.source}")

    image_paths = sorted(
        path
        for path in args.source.rglob("*")
        if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS
    )

    items: list[dict[str, Any]] = []
    summary = {"total": len(image_paths), "generated": 0, "current": 0, "failed": 0, "hasThumbnail": 0}
    generated_at = utc_now()

    for source in image_paths:
        source_rel_from_input = source.relative_to(args.source)
        thumbnail = (args.out / source_rel_from_input).with_suffix(".thumb.webp")
        source_stat = source.stat()
        item: dict[str, Any] = {
            "source": to_posix(source.relative_to(root)),
            "thumbnail": to_posix(thumbnail.relative_to(root)),
            "sourceBytes": source_stat.st_size,
            "sourceMtime": datetime.fromtimestamp(source_stat.st_mtime, timezone.utc).isoformat(timespec="seconds"),
            "updatedAt": generated_at,
        }

        try:
            should_generate = args.force or not thumbnail.exists() or thumbnail.stat().st_mtime < source_stat.st_mtime
            if should_generate:
                dimensions = make_thumbnail(source, thumbnail, (args.width, args.height), args.quality)
                item.update(dimensions)
                item["status"] = "generated"
                summary["generated"] += 1
            else:
                with Image.open(source) as image:
                    item["sourceWidth"], item["sourceHeight"] = image.size
                item["thumbnailWidth"] = args.width
                item["thumbnailHeight"] = args.height
                item["status"] = "current"
                summary["current"] += 1

            item["hasThumbnail"] = True
            item["thumbnailBytes"] = thumbnail.stat().st_size
            summary["hasThumbnail"] += 1
        except Exception as error:  # noqa: BLE001 - keep manifest useful for bad source files.
            item["status"] = "failed"
            item["hasThumbnail"] = False
            item["error"] = str(error)
            summary["failed"] += 1

        items.append(item)

    manifest = {
        "version": 1,
        "generatedAt": generated_at,
        "sourceRoot": to_posix(args.source.relative_to(root)),
        "outputRoot": to_posix(args.out.relative_to(root)),
        "manifestPath": to_posix(args.manifest.relative_to(root)),
        "generatedMap": to_posix(args.map.relative_to(root)),
        "settings": {
            "width": args.width,
            "height": args.height,
            "quality": args.quality,
            "format": "webp",
            "mode": "cover",
        },
        "summary": summary,
        "items": items,
    }

    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    write_ts_map(args.map, items)

    print(
        f"Thumbnail manifest: {to_posix(args.manifest.relative_to(root))} "
        f"({summary['hasThumbnail']}/{summary['total']} ready, {summary['generated']} generated, {summary['failed']} failed)"
    )
    print(f"Thumbnail map: {to_posix(args.map.relative_to(root))}")
    return 0 if summary["failed"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
