// Generated by scripts/generate-thumbnails.py. Do not edit by hand.

import source0 from "../assets/projects/cim/CNC Laser thunail .jpg";
import thumb0 from "../assets/thumbnails/projects/cim/CNC Laser thunail .thumb.webp";
import source1 from "../assets/projects/cim/Digital-Twin-Loading-Station.png";
import thumb1 from "../assets/thumbnails/projects/cim/Digital-Twin-Loading-Station.thumb.webp";
import source2 from "../assets/projects/cim/Inter01.jpg";
import thumb2 from "../assets/thumbnails/projects/cim/Inter01.thumb.webp";
import source3 from "../assets/projects/cim/Inter02.jpg";
import thumb3 from "../assets/thumbnails/projects/cim/Inter02.thumb.webp";
import source4 from "../assets/projects/cim/Inter03.jpg";
import thumb4 from "../assets/thumbnails/projects/cim/Inter03.thumb.webp";
import source5 from "../assets/projects/cim/MR 110 Loading.png";
import thumb5 from "../assets/thumbnails/projects/cim/MR 110 Loading.thumb.webp";
import source6 from "../assets/projects/cim/MR110 CNC Drilling.png";
import thumb6 from "../assets/thumbnails/projects/cim/MR110 CNC Drilling.thumb.webp";
import source7 from "../assets/projects/cim/MR110 CNC Laser.png";
import thumb7 from "../assets/thumbnails/projects/cim/MR110 CNC Laser.thumb.webp";
import source8 from "../assets/projects/cim/MR110 Robot Station Statndalone.png";
import thumb8 from "../assets/thumbnails/projects/cim/MR110 Robot Station Statndalone.thumb.webp";
import source9 from "../assets/projects/cim/MR110 Storage.png";
import thumb9 from "../assets/thumbnails/projects/cim/MR110 Storage.thumb.webp";
import source10 from "../assets/projects/cim/thumnail.jpg";
import thumb10 from "../assets/thumbnails/projects/cim/thumnail.thumb.webp";
import source11 from "../assets/projects/EduLab/EV117 Fuel Outside.jpg";
import thumb11 from "../assets/thumbnails/projects/EduLab/EV117 Fuel Outside.thumb.webp";
import source12 from "../assets/projects/EduLab/EV117 Particles.jpg";
import thumb12 from "../assets/thumbnails/projects/EduLab/EV117 Particles.thumb.webp";
import source13 from "../assets/projects/EduLab/EV117 save screen.jpg";
import thumb13 from "../assets/thumbnails/projects/EduLab/EV117 save screen.thumb.webp";
import source14 from "../assets/projects/EduLab/FM103 Graph.png";
import thumb14 from "../assets/thumbnails/projects/EduLab/FM103 Graph.thumb.webp";
import source15 from "../assets/projects/EduLab/FM103.png";
import thumb15 from "../assets/thumbnails/projects/EduLab/FM103.thumb.webp";
import source16 from "../assets/projects/EduLab/Laminar 02.jpg";
import thumb16 from "../assets/thumbnails/projects/EduLab/Laminar 02.thumb.webp";
import source17 from "../assets/projects/EduLab/Laminar 03.jpg";
import thumb17 from "../assets/thumbnails/projects/EduLab/Laminar 03.thumb.webp";
import source18 from "../assets/projects/EduLab/Laminar.jpg";
import thumb18 from "../assets/thumbnails/projects/EduLab/Laminar.thumb.webp";
import source19 from "../assets/projects/Ivris/ivris app 02.webp";
import thumb19 from "../assets/thumbnails/projects/Ivris/ivris app 02.thumb.webp";
import source20 from "../assets/projects/Ivris/Ivris app 03.webp";
import thumb20 from "../assets/thumbnails/projects/Ivris/Ivris app 03.thumb.webp";
import source21 from "../assets/projects/Ivris/Ivris Website HomePage.png";
import thumb21 from "../assets/thumbnails/projects/Ivris/Ivris Website HomePage.thumb.webp";
import source22 from "../assets/projects/Ivris/Screenshot2025-04-01at8.36.11PM.png";
import thumb22 from "../assets/thumbnails/projects/Ivris/Screenshot2025-04-01at8.36.11PM.thumb.webp";
import source23 from "../assets/projects/Ivris/Screenshot_2025-04-01_at_8.38.02_PM.png";
import thumb23 from "../assets/thumbnails/projects/Ivris/Screenshot_2025-04-01_at_8.38.02_PM.thumb.webp";
import source24 from "../assets/projects/MR109 Compact/MR109 Assembly.png";
import thumb24 from "../assets/thumbnails/projects/MR109 Compact/MR109 Assembly.thumb.webp";
import source25 from "../assets/projects/MR109 Compact/MR109 buffering.png";
import thumb25 from "../assets/thumbnails/projects/MR109 Compact/MR109 buffering.thumb.webp";
import source26 from "../assets/projects/MR109 Compact/MR109 Loading.png";
import thumb26 from "../assets/thumbnails/projects/MR109 Compact/MR109 Loading.thumb.webp";
import source27 from "../assets/projects/MR109 Compact/MR109 Measuring.png";
import thumb27 from "../assets/thumbnails/projects/MR109 Compact/MR109 Measuring.thumb.webp";
import source28 from "../assets/projects/MR109 Compact/MR109 Processing.png";
import thumb28 from "../assets/thumbnails/projects/MR109 Compact/MR109 Processing.thumb.webp";
import source29 from "../assets/projects/MR109 Compact/MR109 Robot Arm.png";
import thumb29 from "../assets/thumbnails/projects/MR109 Compact/MR109 Robot Arm.thumb.webp";
import source30 from "../assets/projects/MR109 Compact/MR109 Sorting.png";
import thumb30 from "../assets/thumbnails/projects/MR109 Compact/MR109 Sorting.thumb.webp";
import source31 from "../assets/projects/MR109 Compact/MR109 Storage.png";
import thumb31 from "../assets/thumbnails/projects/MR109 Compact/MR109 Storage.thumb.webp";
import source32 from "../assets/projects/MR109 Compact/MR109 Transporting.png";
import thumb32 from "../assets/thumbnails/projects/MR109 Compact/MR109 Transporting.thumb.webp";
import source33 from "../assets/projects/Nescafe/Nescafe Sand surfing.jpg";
import thumb33 from "../assets/thumbnails/projects/Nescafe/Nescafe Sand surfing.thumb.webp";
import source34 from "../assets/projects/Nescafe/Nescafe Water Beach.jpg";
import thumb34 from "../assets/thumbnails/projects/Nescafe/Nescafe Water Beach.thumb.webp";
import source35 from "../assets/projects/Nescafe/Nescafe Water Jungle.jpg";
import thumb35 from "../assets/thumbnails/projects/Nescafe/Nescafe Water Jungle.thumb.webp";
import source36 from "../assets/projects/Nescafe/Sand Board Main Menu.jpeg";
import thumb36 from "../assets/thumbnails/projects/Nescafe/Sand Board Main Menu.thumb.webp";
import source37 from "../assets/projects/PID/graph photo.png";
import thumb37 from "../assets/thumbnails/projects/PID/graph photo.thumb.webp";
import source38 from "../assets/projects/PID/MPC 100 Pressure Far.png";
import thumb38 from "../assets/thumbnails/projects/PID/MPC 100 Pressure Far.thumb.webp";
import source39 from "../assets/projects/PID/MPC 101 Temp.png";
import thumb39 from "../assets/thumbnails/projects/PID/MPC 101 Temp.thumb.webp";
import source40 from "../assets/projects/PID/MPC 102 Speed far.png";
import thumb40 from "../assets/thumbnails/projects/PID/MPC 102 Speed far.thumb.webp";
import source41 from "../assets/projects/PID/MPC 102 Speed.png";
import thumb41 from "../assets/thumbnails/projects/PID/MPC 102 Speed.thumb.webp";
import source42 from "../assets/projects/PID/MPC 103 DC Motor.png";
import thumb42 from "../assets/thumbnails/projects/PID/MPC 103 DC Motor.thumb.webp";
import source43 from "../assets/projects/PID/MPC 105 Flow.png";
import thumb43 from "../assets/thumbnails/projects/PID/MPC 105 Flow.thumb.webp";
import source44 from "../assets/projects/PID/MPC104 Level.png";
import thumb44 from "../assets/thumbnails/projects/PID/MPC104 Level.thumb.webp";

const thumbnailPairs: [string, string][] = [
  [source0, thumb0],
  [source1, thumb1],
  [source2, thumb2],
  [source3, thumb3],
  [source4, thumb4],
  [source5, thumb5],
  [source6, thumb6],
  [source7, thumb7],
  [source8, thumb8],
  [source9, thumb9],
  [source10, thumb10],
  [source11, thumb11],
  [source12, thumb12],
  [source13, thumb13],
  [source14, thumb14],
  [source15, thumb15],
  [source16, thumb16],
  [source17, thumb17],
  [source18, thumb18],
  [source19, thumb19],
  [source20, thumb20],
  [source21, thumb21],
  [source22, thumb22],
  [source23, thumb23],
  [source24, thumb24],
  [source25, thumb25],
  [source26, thumb26],
  [source27, thumb27],
  [source28, thumb28],
  [source29, thumb29],
  [source30, thumb30],
  [source31, thumb31],
  [source32, thumb32],
  [source33, thumb33],
  [source34, thumb34],
  [source35, thumb35],
  [source36, thumb36],
  [source37, thumb37],
  [source38, thumb38],
  [source39, thumb39],
  [source40, thumb40],
  [source41, thumb41],
  [source42, thumb42],
  [source43, thumb43],
  [source44, thumb44],
];

export const generatedThumbnails = new Map<string, string>(thumbnailPairs);

export const getGeneratedThumbnail = (source: string | undefined, fallback = "") => {
  if (!source) return fallback;
  return (generatedThumbnails.get(source) ?? fallback) || source;
};
